name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to deploy, must be either `main` or `next`.'
        required: true
        default: 'main'

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub event
        run: cat $GITHUB_EVENT_PATH
