name: Deploy

on:
  repository_dispatch:
    types:
      - deploy

concurrency:
  group: deploy-${{ github.event.client_payload.stage }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Event
        run: cat $GITHUB_EVENT_PATH

      - name: Configure
        id: config
        run: |
          STAGE="${{ github.event.client_payload.stage }}"

          if [ "$STAGE" == "prod" ]; then
            BRANCH=refs/heads/main
          elif [ "$STAGE" == "next" ]; then
            BRANCH=refs/heads/next
          else
            echo "Unknown stage: $STAGE"
            exit 1
          fi

          echo "branch: $BRANCH"
          echo "::set-output name=branch::${BRANCH}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.config.outputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Select Pulumi stack
        run: |
          stack=$(node scripts/get-stack-name.js)
          echo "Pulumi stack: ${stack}"
        working-directory: infrastructure
