name: Deploy

on:
  push:
  repository_dispatch:
    types:
      - deploy

concurrency:
  group: deploy-${{ github.event.client_payload.stage }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        id: config
        run: |
          if [ "${{ github.event.action }}" == "deploy" ]; then
            # Determine the branch name from the dispatch event.
            STAGE="${{ github.event.client_payload.stage }}"

            if [ "$STAGE" == "prod" ]; then
              REF="refs/heads/main"
            elif [ "$STAGE" == "next" ]; then
              REF="refs/heads/next"
            else
              echo "Unknown stage: $STAGE"
              exit 1
            fi
          else
            # This build was not triggered by a dispatch event but a push
            # or PR, so we simply continue with the current ref.
            REF="${{ github.ref }}"
          fi

          echo "Git ref: $REF"
          echo "::set-output name=ref::${REF}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.config.outputs.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Select Pulumi stack
        run: |
          stack=$(node scripts/get-stack-name.js)
          echo "Pulumi stack: ${stack}"
        working-directory: infrastructure
